apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    io.kompose.service: postgres
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: keycloak
        - name: POSTGRESQL_PASSWORD
          value: keycloak
        - name: POSTGRESQL_DATABASE
          value: keycloak
        - name: "CHE_POSTGRES_USERNAME"
          value: "pgche"
        - name: "CHE_POSTGRES_PASSWORD"
          value: "pgchepassword"
        - name: "CHE_POSTGRES_DATABASE"
          value: "dbche"
        image: ' '
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: postgres-data
      restartPolicy: Always
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - postgres
      from:
        kind: ImageStreamTag
        name: postgres:latest
    type: ImageChange
status: {}

